kind: pipeline
type: docker
name: deploy

steps:

- name: build
  image: golang:1.16.0-alpine3.13
  commands:
  - go run .
  environment:
    BUILD_SITE: true

- name: push
  image: alpine/git:v2.30.1
  environment:
    DEPLOY_KEY:
      from_secret: github_deploy_key
    GIT_COMMITTER_EMAIL: 69285523+bottbottbott@users.noreply.github.com
    GIT_COMMITTER_NAME: bottbottbott
  commands:
  - git add -f .
  - git commit -m '[drone] build site'
  - mkdir -p /root/.ssh
  - echo "$DEPLOY_KEY" > /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa
  - touch /root/.ssh/known_hosts
  - chmod 600 /root/.ssh/known_hosts
  - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
  - git push -f git@github.com:trotttrotttrott/dullspecies.com HEAD:build

trigger:
  event:
  - push
  branch:
  - main
  repo:
  - trotttrotttrott/dullspecies.com
